
title: CodeCarrot Garage - Online Marketing, Web Design, and Small Business Blog
email: contact@codecarrot.net
description: The CodeCarrot Garage offers in-depth articles about websites, online marketing, business and more.
baseurl: ""
url: "http://blog.codecarrot.net/"
twitter:
  username: codecarrotnet
github:
  username:  codecarrotnet
logo: "http://www.codecarrot.net/assets/images/footer/codecarrot.png"
webmaster_verifications:
  google: 4YT4xkzM4wsDqWQY6J6LQplYCKTXAgI410kIAGE22VA
facebook:
 app_id: 181159655729057

permalink: /:title/ 

paginate_path: "/page/:num/"
paginate: 9

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
